# Generated by Django 6.1 on 2026-08-13 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('cutoff_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'slots',
                'ordering': ['date', 'start_time'],
                'unique_together': {('date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='SlotItemCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_units', models.PositiveIntegerField(default=20)),
                ('units_booked', models.PositiveIntegerField(default=0)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_capacities', to='menu.menuitem')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='slots.slot')),
            ],
            options={
                'db_table': 'slot_item_capacities',
                'unique_together': {('slot', 'menu_item')},
            },
        ),
    ]
